development:
  adapter: postgresql
  encoding: unicode
  database: grid_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: grid_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: grid_production
  pool: 5